apiVersion: xcp.tetrate.io/v2
kind: GlobalSetting
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"xcp.tetrate.io/v2","kind":"GlobalSetting","metadata":{"annotations":{},"name":"global","namespace":"xcp-system"},"spec":{"networkSettings":{"networkReachability":{"nw-cluster-0":"nw-cluster-1","nw-cluster-1":"nw-cluster-0,nw-cluster-2","nw-cluster-2":"nw-cluster-1"}}}}
  creationTimestamp: "2026-05-20T18:49:04Z"
  generation: 2
  managedFields:
  - apiVersion: xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:networkSettings:
          .: {}
          f:networkReachability:
            .: {}
            f:nw-cluster-0: {}
            f:nw-cluster-1: {}
            f:nw-cluster-2: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-05-27T08:21:05Z"
  name: global
  namespace: xcp-system
  resourceVersion: "899686"
  uid: 94dafcb4-f992-426d-91df-84e18870bec6
spec:
  networkSettings:
    networkReachability:
      nw-cluster-0: nw-cluster-1
      nw-cluster-1: nw-cluster-0,nw-cluster-2
      nw-cluster-2: nw-cluster-1
