apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  annotations:
    xcp.tetrate.io/contentHash: e92850b1e6b8980840d6c596ad130d3c
  creationTimestamp: "2026-06-01T10:49:27Z"
  generation: 1
  labels:
    istio.io/rev: global
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
      f:spec:
        .: {}
        f:exportTo: {}
        f:host: {}
        f:trafficPolicy:
          .: {}
          f:portLevelSettings: {}
    manager: xcpd
    operation: Update
    time: "2026-06-01T10:49:27Z"
  name: global-gateway-echo-term-tetrate-io
  namespace: xcp-multicluster
  resourceVersion: "2088415"
  uid: de24697a-84d1-4765-b9ff-fc5104ea90f4
spec:
  exportTo:
  - '*'
  host: echo-term.tetrate.io
  trafficPolicy:
    portLevelSettings:
    - connectionPool:
        http:
          useClientProtocol: true
      loadBalancer:
        localityLbSetting:
          enabled: true
          failoverPriority:
          - topology.kubernetes.io/region
          - topology.istio.io/network
          - topology.kubernetes.io/zone
          - topology.istio.io/subzone
      outlierDetection:
        consecutiveGatewayErrors: 10
        maxEjectionPercent: 100
      port:
        number: 80
      tls:
        mode: ISTIO_MUTUAL
        sni: echo-term.tetrate.io
