apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"IngressGateway","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/gatewayGroup":"tier2-gg","xcp.tetrate.io/workspace":"passthrough-ws"},"name":"echo-t2-gw","namespace":"xcp-system"},"spec":{"tls":[{"hostname":"echo.tetrate.io","name":"echo","port":17443,"route":{"host":"echo/echo.echo.svc.cluster.local","port":9443}}],"workloadSelector":{"labels":{"app":"echo-gateway"},"namespace":"echo"}}}
    xcp.tetrate.io/contentHash: c6d0ee646c280e4d57e4dcc878bf038a
  creationTimestamp: "2026-05-28T14:33:06Z"
  generation: 1
  labels:
    istio.io/rev: global
    xcp.tetrate.io/gatewayGroup: tier2-gg
    xcp.tetrate.io/workspace: passthrough-ws
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
          f:xcp.tetrate.io/gatewayGroup: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:configPatches: {}
        f:priority: {}
        f:workloadSelector:
          .: {}
          f:labels:
            .: {}
            f:app: {}
    manager: xcpd
    operation: Update
    time: "2026-05-28T14:33:06Z"
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:observedGeneration: {}
        f:validationMessages: {}
    manager: pilot-discovery
    operation: Update
    subresource: status
    time: "2026-05-28T14:33:07Z"
  name: default-allow-echo-t2-gw-external-batch0
  namespace: echo
  resourceVersion: "966194"
  uid: ab3b9ee2-0094-490c-a5fc-d24d6afdb6f5
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.rbac
          sni: echo.tetrate.io
        portNumber: 17443
      proxy:
        proxyVersion: ^1\.(22|24|28)(\.\d+)?(-.*)?$
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.rbac
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
          rules:
            policies:
              echo-echo-t2-gw-echo:
                permissions:
                - and_rules:
                    rules:
                    - or_rules:
                        rules:
                        - destination_port: 17443
                principals:
                - and_ids:
                    ids:
                    - any: true
          stat_prefix: tcp.
  priority: -2000
  workloadSelector:
    labels:
      app: echo-gateway
status:
  observedGeneration: "1"
  validationMessages:
  - documentationUrl: https://istio.io/v1.28/docs/reference/config/analysis/ist0133/
    level: WARNING
    type:
      code: IST0133
