apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  annotations:
    xcp.tetrate.io/contentHash: db923d57163ed5e5563ab3e289bba8b6
  creationTimestamp: "2026-05-28T14:33:08Z"
  generation: 1
  labels:
    istio.io/rev: global
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:addresses: {}
    manager: pilot-discovery
    operation: Update
    subresource: status
    time: "2026-05-28T14:33:08Z"
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
      f:spec:
        .: {}
        f:endpoints: {}
        f:exportTo: {}
        f:hosts: {}
        f:location: {}
        f:ports:
          .: {}
          k:{"name":"tls-17443"}:
            .: {}
            f:name: {}
            f:number: {}
            f:protocol: {}
        f:resolution: {}
        f:subjectAltNames: {}
    manager: xcpd
    operation: Update
    time: "2026-05-28T14:33:08Z"
  name: global-gateway-echo-tetrate-io
  namespace: xcp-multicluster
  resourceVersion: "966205"
  uid: 5f91fd36-ca86-4078-a0d2-cd32a729bb95
spec:
  endpoints:
  - address: 10.255.20.235
    labels:
      xcp.tetrate.io/cluster: cluster-1
      xcp.tetrate.io/hops: "0"
      xcp.tetrate.io/service: echo-gateway.echo.svc.cluster.local
      xcp.tetrate.io/serviceType: localGateway
      xcp.tetrate.io/svc-port-17443: "true"
    locality: us-east1/us-east1-B/subzone-x
    network: nw-cluster-1
    ports:
      tls-17443: 17443
  exportTo:
  - '*'
  hosts:
  - echo.tetrate.io
  location: MESH_INTERNAL
  ports:
  - name: tls-17443
    number: 17443
    protocol: TLS
  resolution: STATIC
  subjectAltNames:
  - spiffe://cluster.local/ns/echo/sa/echo-gateway-service-account
status:
  addresses:
  - host: echo.tetrate.io
    value: 240.240.0.10
  - host: echo.tetrate.io
    value: 2001:2::a
