apiVersion: gateway.xcp.tetrate.io/v2
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"Gateway","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/gatewayGroup":"transit-mid-gg","xcp.tetrate.io/workspace":"transit-ws"},"name":"transit-mid-gw","namespace":"xcp-system"},"spec":{"http":[{"hostname":"echo.echo-tr.svc.cluster.local","name":"transit-hop","routing":{"rules":[{"route":{"clusterDestination":{"clusters":[{"name":"cluster-2","weight":100}]}}}]},"transit":true}],"workloadSelector":{"labels":{"app":"transit-tier1-gateway"},"namespace":"transit"}}}
  creationTimestamp: "2026-05-28T14:50:11Z"
  generation: 1
  labels:
    xcp.tetrate.io/gatewayGroup: transit-mid-gg
    xcp.tetrate.io/workspace: transit-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/gatewayGroup: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:http: {}
        f:workloadSelector:
          .: {}
          f:labels:
            .: {}
            f:app: {}
          f:namespace: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-05-28T14:50:11Z"
  name: transit-mid-gw
  namespace: xcp-system
  resourceVersion: "1312284"
  uid: 6a7552ae-d12f-4334-8de5-0477d547f142
spec:
  http:
  - hostname: echo.echo-tr.svc.cluster.local
    name: transit-hop
    routing:
      rules:
      - route:
          clusterDestination:
            clusters:
            - name: cluster-2
              weight: 100
    transit: true
  workloadSelector:
    labels:
      app: transit-tier1-gateway
    namespace: transit
