apiVersion: gateway.xcp.tetrate.io/v2
kind: GatewayGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"GatewayGroup","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/workspace":"term-ws"},"name":"tier1-term-gg","namespace":"xcp-system"},"spec":{"configMode":"BRIDGED","namespaceSelector":{"names":["cluster-0/tier1-term"]}}}
    xcp.tetrate.io/contentHash: 9371fe8fe4c9fd1813a86d8a07c8a3ff
  creationTimestamp: "2026-05-25T10:50:00Z"
  generation: 1
  labels:
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: xcpd
    operation: Update
    time: "2026-05-25T10:50:00Z"
  name: tier1-term-gg
  namespace: istio-system
  resourceVersion: "619406"
  uid: 37674b9f-2977-4253-9a43-6c17ac4658b9
spec:
  namespaceSelector:
    names:
    - cluster-0/tier1-term
