# GatewayGroup for the Tier1 gateway in the TERMINATING scenario.
#
# Apply to: XCP Central -> cluster-0, namespace xcp-system
apiVersion: gateway.xcp.tetrate.io/v2
kind: GatewayGroup
metadata:
  name: tier1-term-gg
  namespace: xcp-system
  labels:
    xcp.tetrate.io/workspace: term-ws
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
      - cluster-0/tier1-term
