apiVersion: gateway.xcp.tetrate.io/v2
kind: Tier1Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"Tier1Gateway","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/gatewayGroup":"tier1-term-gg","xcp.tetrate.io/workspace":"term-ws"},"name":"tier1-echo-term-gw","namespace":"xcp-system"},"spec":{"externalServers":[{"clusters":[{"name":"cluster-1","weight":100}],"hostname":"echo-term.tetrate.io","name":"echo","port":18443,"tls":{"mode":"SIMPLE","secretName":"echo-term-edge-tls"}}],"workloadSelector":{"labels":{"app":"tier1-term-gateway"},"namespace":"tier1-term"}}}
  creationTimestamp: "2026-05-28T14:44:41Z"
  generation: 1
  labels:
    xcp.tetrate.io/gatewayGroup: tier1-term-gg
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/gatewayGroup: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:externalServers: {}
        f:workloadSelector:
          .: {}
          f:labels:
            .: {}
            f:app: {}
          f:namespace: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-05-28T14:44:41Z"
  name: tier1-echo-term-gw
  namespace: xcp-system
  resourceVersion: "1310768"
  uid: 464eb10a-1a2b-498b-9f48-fd72f02e7fea
spec:
  externalServers:
  - clusters:
    - name: cluster-1
      weight: 100
    hostname: echo-term.tetrate.io
    name: echo
    port: 18443
    tls:
      mode: SIMPLE
      secretName: echo-term-edge-tls
  workloadSelector:
    labels:
      app: tier1-term-gateway
    namespace: tier1-term
