apiVersion: gateway.xcp.tetrate.io/v2
kind: GatewayGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"GatewayGroup","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/workspace":"transit-ws"},"name":"transit-mid-gg","namespace":"xcp-system"},"spec":{"configMode":"BRIDGED","namespaceSelector":{"names":["cluster-1/transit"]}}}
    xcp.tetrate.io/contentHash: aaec32087660f62e52affa158c256424
  creationTimestamp: "2026-05-28T15:04:36Z"
  generation: 1
  labels:
    xcp.tetrate.io/workspace: transit-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: xcpd
    operation: Update
    time: "2026-05-28T15:04:36Z"
  name: transit-mid-gg
  namespace: istio-system
  resourceVersion: "972493"
  uid: 8766268d-dc85-421d-ac13-de6a1b2de7ca
spec:
  namespaceSelector:
    names:
    - cluster-1/transit
