apiVersion: gateway.xcp.tetrate.io/v2
kind: GatewayGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"GatewayGroup","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/workspace":"term-ws"},"name":"tier2-term-gg","namespace":"xcp-system"},"spec":{"configMode":"BRIDGED","namespaceSelector":{"names":["cluster-1/echo-term"]}}}
    xcp.tetrate.io/contentHash: 74c8dcf6aa782005d720db9fd5228d2a
  creationTimestamp: "2026-05-23T07:30:12Z"
  generation: 1
  labels:
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: xcpd
    operation: Update
    time: "2026-05-23T07:30:12Z"
  name: tier2-term-gg
  namespace: istio-system
  resourceVersion: "269004"
  uid: 9def1980-ba8f-45d3-b8d6-ee05ca069bdd
spec:
  namespaceSelector:
    names:
    - cluster-1/echo-term
