apiVersion: xcp.tetrate.io/v2
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"xcp.tetrate.io/v2","kind":"Workspace","metadata":{"annotations":{},"name":"passthrough-ws","namespace":"xcp-system"},"spec":{"namespaceSelector":{"names":["cluster-0/tier1","cluster-1/echo"]}}}
    xcp.tetrate.io/contentHash: e5d3817c7d08543139c22f8de5bfec93
  creationTimestamp: "2026-05-25T10:44:25Z"
  generation: 1
  managedFields:
  - apiVersion: xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
      f:spec:
        .: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: xcpd
    operation: Update
    time: "2026-05-25T10:44:25Z"
  name: passthrough-ws
  namespace: istio-system
  resourceVersion: "458344"
  uid: 5abd6ec7-f840-498f-8d9c-1380729e8bb1
spec:
  namespaceSelector:
    names:
    - cluster-0/tier1
    - cluster-1/echo
