apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  annotations:
    xcp.tetrate.io/contentHash: 19e4cd75717fef91a95ead90831c2486
  creationTimestamp: "2026-05-28T14:47:27Z"
  generation: 1
  labels:
    istio.io/rev: global
    xcp.tetrate.io/eastWestGateway: "true"
    xcp.tetrate.io/workspace: xc-ws
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
          f:xcp.tetrate.io/eastWestGateway: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:selector:
          .: {}
          f:app: {}
        f:servers: {}
    manager: xcpd
    operation: Update
    time: "2026-05-28T14:47:27Z"
  name: ewgen-xc-ws-0
  namespace: backend-c1
  resourceVersion: "969113"
  uid: 57577942-6f3c-4f7a-a94d-562068a9c40b
spec:
  selector:
    app: ew-gateway
  servers:
  - hosts:
    - backend.backend-c1.svc.cluster.local
    name: ew-autopassthrough
    port:
      name: mtls-autopassthrough
      number: 15443
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
