apiVersion: gateway.xcp.tetrate.io/v2
kind: GatewayGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"GatewayGroup","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/workspace":"term-ws"},"name":"tier1-term-gg","namespace":"xcp-system"},"spec":{"configMode":"BRIDGED","namespaceSelector":{"names":["cluster-0/tier1-term"]}}}
  creationTimestamp: "2026-05-25T10:49:59Z"
  generation: 1
  labels:
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:configMode: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-05-25T10:49:59Z"
  name: tier1-term-gg
  namespace: xcp-system
  resourceVersion: "619397"
  uid: ab0e73e4-fe39-41fe-a19f-7888e5f28d3e
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
    - cluster-0/tier1-term
