apiVersion: xcp.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"xcp.tetrate.io/v2","kind":"WorkspaceSetting","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/workspace":"xc-ws"},"name":"xc-ws-settings","namespace":"xcp-system"},"spec":{"defaultEastWestGatewaySettings":[{"exposedServices":[{"serviceLabels":{"app":"backend"}}],"workloadSelector":{"labels":{"app":"ew-gateway"},"namespace":"backend-c1"}}]}}
  creationTimestamp: "2026-05-25T10:54:58Z"
  generation: 1
  labels:
    xcp.tetrate.io/workspace: xc-ws
  managedFields:
  - apiVersion: xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:defaultEastWestGatewaySettings: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-05-25T10:54:58Z"
  name: xc-ws-settings
  namespace: xcp-system
  resourceVersion: "620683"
  uid: aeb7b9d1-250b-4c5d-926c-346cdccdfe6d
spec:
  defaultEastWestGatewaySettings:
  - exposedServices:
    - serviceLabels:
        app: backend
    workloadSelector:
      labels:
        app: ew-gateway
      namespace: backend-c1
