apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"Tier1Gateway","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/gatewayGroup":"tier1-term-gg","xcp.tetrate.io/workspace":"term-ws"},"name":"tier1-echo-term-gw","namespace":"xcp-system"},"spec":{"externalServers":[{"clusters":[{"name":"cluster-1","weight":100}],"hostname":"echo-term.tetrate.io","name":"echo","port":18443,"tls":{"mode":"SIMPLE","secretName":"echo-term-edge-tls"}}],"workloadSelector":{"labels":{"app":"tier1-term-gateway"},"namespace":"tier1-term"}}}
    xcp.tetrate.io/contentHash: 4798f0573a57090b1a140595d40dabe8
  creationTimestamp: "2026-05-25T10:50:01Z"
  generation: 1
  labels:
    istio.io/rev: global
    xcp.tetrate.io/gatewayGroup: tier1-term-gg
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
          f:xcp.tetrate.io/gatewayGroup: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:exportTo: {}
        f:gateways: {}
        f:hosts: {}
        f:http: {}
    manager: xcpd
    operation: Update
    time: "2026-05-25T10:50:01Z"
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:observedGeneration: {}
    manager: pilot-discovery
    operation: Update
    subresource: status
    time: "2026-05-25T10:50:02Z"
  name: tier1-echo-term-gw-echo
  namespace: tier1-term
  resourceVersion: "619475"
  uid: 12ce396e-2aed-42b0-95ec-af6a3b3877b6
spec:
  exportTo:
  - .
  gateways:
  - tier1-term/tier1-echo-term-gw
  hosts:
  - echo-term.tetrate.io
  http:
  - match:
    - port: 18443
    name: tier1-echo-term-gw-echo-external
    rewrite:
      authority: echo-term.tetrate.io
    route:
    - destination:
        host: echo-term.tetrate.io
        port:
          number: 80
        subset: tier1-echo-term-gw-echo-external-0
      weight: 100
status:
  observedGeneration: "1"
