apiVersion: xcp.tetrate.io/v2
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"xcp.tetrate.io/v2","kind":"Workspace","metadata":{"annotations":{},"name":"transit-ws","namespace":"xcp-system"},"spec":{"namespaceSelector":{"names":["cluster-0/client-tr","cluster-1/transit","cluster-2/echo-tr"]}}}
  creationTimestamp: "2026-05-28T15:04:35Z"
  generation: 1
  managedFields:
  - apiVersion: xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-05-28T15:04:35Z"
  name: transit-ws
  namespace: xcp-system
  resourceVersion: "1315752"
  uid: e79b162b-dcb9-4e8f-b4dc-da47c4c71319
spec:
  namespaceSelector:
    names:
    - cluster-0/client-tr
    - cluster-1/transit
    - cluster-2/echo-tr
