apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"IngressGateway","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/gatewayGroup":"tier2-term-gg","xcp.tetrate.io/workspace":"term-ws"},"name":"echo-t2-term-gw","namespace":"xcp-system"},"spec":{"http":[{"hostname":"echo-term.tetrate.io","name":"echo","port":8080,"routing":{"rules":[{"route":{"host":"echo-term/echo-term.echo-term.svc.cluster.local","port":80}}]}}],"workloadSelector":{"labels":{"app":"echo-term-gateway"},"namespace":"echo-term"}}}
    xcp.tetrate.io/contentHash: 927e14370db8eee6b10f33b22f2a997e
  creationTimestamp: "2026-05-28T14:44:43Z"
  generation: 1
  labels:
    istio.io/rev: global
    xcp.tetrate.io/gatewayGroup: tier2-term-gg
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
          f:xcp.tetrate.io/gatewayGroup: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:configPatches: {}
        f:priority: {}
        f:workloadSelector:
          .: {}
          f:labels:
            .: {}
            f:app: {}
    manager: xcpd
    operation: Update
    time: "2026-05-28T14:44:43Z"
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:observedGeneration: {}
        f:validationMessages: {}
    manager: pilot-discovery
    operation: Update
    subresource: status
    time: "2026-05-28T14:44:46Z"
  name: default-allow-echo-t2-term-gw-external-batch0
  namespace: echo-term
  resourceVersion: "968479"
  uid: f7ae6ca0-caa5-4988-921f-3c9795ee0d83
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.rbac
        portNumber: 8080
      proxy:
        proxyVersion: ^1\.(22|24|28)(\.\d+)?(-.*)?$
    patch:
      operation: MERGE
      value:
        name: envoy.filters.http.rbac
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
          rules:
            policies:
              echo-term-echo-t2-term-gw-echo:
                permissions:
                - and_rules:
                    rules:
                    - or_rules:
                        rules:
                        - header:
                            name: :authority
                            string_match:
                              exact: echo-term.tetrate.io
                              ignore_case: true
                        - header:
                            name: :authority
                            string_match:
                              exact: echo-term.tetrate.io:8080
                              ignore_case: true
                    - or_rules:
                        rules:
                        - destination_port: 8080
                principals:
                - and_ids:
                    ids:
                    - any: true
  priority: -2000
  workloadSelector:
    labels:
      app: echo-term-gateway
status:
  observedGeneration: "1"
  validationMessages:
  - documentationUrl: https://istio.io/v1.28/docs/reference/config/analysis/ist0133/
    level: WARNING
    type:
      code: IST0133
