apiVersion: gateway.xcp.tetrate.io/v2
kind: GatewayGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"GatewayGroup","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/workspace":"term-ws"},"name":"tier2-term-gg","namespace":"xcp-system"},"spec":{"configMode":"BRIDGED","namespaceSelector":{"names":["cluster-1/echo-term"]}}}
  creationTimestamp: "2026-06-01T10:49:17Z"
  generation: 1
  labels:
    xcp.tetrate.io/workspace: term-ws
  managedFields:
  - apiVersion: gateway.xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:configMode: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-06-01T10:49:17Z"
  name: tier2-term-gg
  namespace: xcp-system
  resourceVersion: "2088343"
  uid: 2c869f3e-7ee8-4f11-981a-dbc0bc95ebe3
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
    - cluster-1/echo-term
