apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.xcp.tetrate.io/v2","kind":"Tier1Gateway","metadata":{"annotations":{},"labels":{"xcp.tetrate.io/gatewayGroup":"tier1-gg","xcp.tetrate.io/workspace":"passthrough-ws"},"name":"tier1-echo-gw","namespace":"xcp-system"},"spec":{"passthroughServers":[{"clusters":[{"name":"cluster-1","weight":100}],"hostname":"echo.tetrate.io","name":"echo","port":17443}],"workloadSelector":{"labels":{"app":"tier1-gateway"},"namespace":"tier1"}}}
    xcp.tetrate.io/contentHash: 77c33e466d45d4f2a5b8afb837988ddb
  creationTimestamp: "2026-05-28T14:33:06Z"
  generation: 1
  labels:
    istio.io/rev: global
    xcp.tetrate.io/gatewayGroup: tier1-gg
    xcp.tetrate.io/workspace: passthrough-ws
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
        f:labels:
          .: {}
          f:istio.io/rev: {}
          f:xcp.tetrate.io/gatewayGroup: {}
          f:xcp.tetrate.io/workspace: {}
      f:spec:
        .: {}
        f:exportTo: {}
        f:gateways: {}
        f:hosts: {}
        f:tls: {}
    manager: xcpd
    operation: Update
    time: "2026-05-28T14:33:06Z"
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:observedGeneration: {}
    manager: pilot-discovery
    operation: Update
    subresource: status
    time: "2026-05-28T14:33:07Z"
  name: tier1-echo-gw-echo
  namespace: tier1
  resourceVersion: "1308014"
  uid: 7f5324b6-a01f-493f-a693-20b3f1ea5c09
spec:
  exportTo:
  - .
  gateways:
  - tier1/tier1-echo-gw
  hosts:
  - echo.tetrate.io
  tls:
  - match:
    - port: 17443
      sniHosts:
      - echo.tetrate.io
    route:
    - destination:
        host: echo.tetrate.io
        port:
          number: 17443
        subset: tier1-echo-gw-echo-passthrough-0
      weight: 100
status:
  observedGeneration: "1"
