apiVersion: xcp.tetrate.io/v2
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"xcp.tetrate.io/v2","kind":"Workspace","metadata":{"annotations":{},"name":"passthrough-ws","namespace":"xcp-system"},"spec":{"namespaceSelector":{"names":["cluster-0/tier1","cluster-1/echo"]}}}
    xcp.tetrate.io/contentHash: e5d3817c7d08543139c22f8de5bfec93
  creationTimestamp: "2026-06-01T10:48:33Z"
  generation: 1
  managedFields:
  - apiVersion: xcp.tetrate.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:xcp.tetrate.io/contentHash: {}
      f:spec:
        .: {}
        f:namespaceSelector:
          .: {}
          f:names: {}
    manager: xcpd
    operation: Update
    time: "2026-06-01T10:48:33Z"
  name: passthrough-ws
  namespace: istio-system
  resourceVersion: "2087994"
  uid: c31d8250-b07f-45d5-bb6a-26c654aff491
spec:
  namespaceSelector:
    names:
    - cluster-0/tier1
    - cluster-1/echo
